### ISSUE TITLE
Verifier evaluate fails due to trailing characters

### ISSUE THREAD

**Issue by c3d** [confidential-containers/kbs#180] opened 2023-10-03 09:41 UTC
Reported by @uril following the quickstart guide on Azure, he got a message

```
Attestation failed: Verifier evaluate failed: json parse error\n\nCaused by:\n	trailing characters at line 1 column 420"
```

Here are the steps he reported doing:

* Started a confidential Ubuntu VM on Azure and tested with it - using a container.
* Created a container image based on CoCo existing image but built with openssl and added kbs-client (quay.io/uril/coco-kbs-pubkey – currently private)
* When attesting, the kbs-client program must be run as root, as it needs access to `/dev/tpm0`.
* Tested it - similar to what I did on my laptop (following kbs/quickstart.md), but without the environment-variable (AA_SAMPLE_ATTESTER_TEST=yes) so it’s actually doing attestation.
* Attestation protocol is running but fails for me with an error message:
```
Attestation failed: Verifier evaluate failed: json parse error\n\nCaused by:\n	trailing characters at line 1 column 420"
```

I did not find an issue with a similar report. The parsing seems to be done by `public_key_from_pem`, which is code expanded from an openssl crate. So it looks like there is a bit of fussiness of this parser when there is extra trailing characters.

**Comment by mkulke** [comment] 2023-11-14 13:34
@c3d Hello Christophe, can you confirm the issue is fixed for you?

**Comment by fitzthum** [comment] 2024-02-20 18:36
I think this is fixed now. If not, please reopen.

**Closed by fitzthum** 2024-02-20 18:36 UTC
