### ISSUE TITLE
Nightly Build Problems

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/kbs#322] opened 2024-02-12 14:52 UTC
We have some problems with the nightly builds. The root of this is an issue in the `ahash` crate that was fixed in `v0.8.7`. Unfortunately there is one crate that indirectly requires an earlier version.

The crate in question is `mobc`. which pulls in an old version of `metrics`. The `metrics` crate has already [fixed the issue](https://github.com/metrics-rs/metrics/commit/f7e979a1b648e0dd8b25ff179c11ce5e15727fcc) but `mobc` hasn't updated to use the new version. I will see if I can get a PR into that repo, which doesn't seem super active.

**Comment by fitzthum** [comment] 2024-02-12 15:36
Made a [PR in mobc](https://github.com/importcjj/mobc/pull/91).

**Comment by mkulke** [comment] 2024-02-16 08:07
The issue is fixed now by regenerating the cargo lockfile 👍

**Closed by mkulke** 2024-02-16 08:07 UTC
